USE wordpress;
DROP TABLE wp_commentmeta;
DROP TABLE wp_comments;
DROP TABLE wp_links;
DROP TABLE wp_options;
DROP TABLE wp_postmeta;
DROP TABLE wp_posts;
DROP TABLE wp_termmeta;
DROP TABLE wp_terms;
DROP TABLE wp_term_relationships;
DROP TABLE wp_term_taxonomy;